name: Build and test lang-dot package

on:
  push:
    branches-ignore:
      - v2
      - gh-pages
    paths:
      - "packages/lang-dot/**"
  workflow_call: {}

permissions:
  contents: read

jobs:
  build:
    name: Build and test lang-dot package
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: "Run build and test"
        run: |
          npm clean-install
          npm run build
          npm run test
        working-directory: packages/lang-dot

      - uses: actions/upload-artifact@v4
        with:
          name: dist
          path: packages/lang-dot/dist

  test-types:
    name: Test types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: "Install in package directory"
        run: |
          npm clean-install
        working-directory: packages/lang-dot

      - name: "Run check-types"
        run: |
          npm clean-install
          npm run check-types
        working-directory: packages/lang-dot/test/types
